In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
# -----------------------------
# 1. Load Data
# -----------------------------
df = pd.read_csv("/Users/shubhangipanda/Documents/Projects/ml-pipelines/data/raw/Churn.csv")

In [4]:
print("Shape before cleaning:", df.shape)
df.head()

Shape before cleaning: (7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
# 2. Handle Missing Values
# -----------------------------
# "TotalCharges" is numeric but stored as object (some empty strings)
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [7]:
# 3. Drop Irrelevant Columns
# -----------------------------
# 'customerID' is just an identifier
df.drop("customerID", axis=1, inplace=True)

In [8]:
# 4. Encode Categorical Variables
# -----------------------------
# Binary columns: Yes/No → 1/0
binary_cols = [col for col in df.columns if df[col].nunique() == 2]

In [9]:
for col in binary_cols:
    df[col] = df[col].map({"Yes": 1, "No": 0})

In [10]:
# Multi-category columns: use LabelEncoder
cat_cols = df.select_dtypes(include=["object"]).columns.tolist()

In [12]:
print(cat_cols)

['MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']

In [13]:

le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [14]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,NaN,NaN,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0
1,NaN,NaN,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0
2,NaN,NaN,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1
3,NaN,NaN,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0
4,NaN,NaN,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1

In [15]:
# 5. Scale Numerical Features
# -----------------------------
num_cols = ["tenure", "MonthlyCharges", "TotalCharges"]

In [16]:
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [21]:
# 6. Save Cleaned Data
# -----------------------------
df.to_csv("/Users/shubhangipanda/Documents/Projects/ml-pipelines/data/processed/Churn.csv", index=False)

In [23]:
print("Shape after cleaning:", df.shape)
df.head()

Shape after cleaning: (7043, 20)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,NaN,NaN,1,0,-1.277445,0,1,0,0,2,0,0,0,0,0,1,2,-1.160323,-0.994194,0
1,NaN,NaN,0,0,0.066327,1,0,0,2,0,2,0,0,0,1,0,3,-0.259629,-0.173740,0
2,NaN,NaN,0,0,-1.236724,1,0,0,2,2,0,0,0,0,0,1,3,-0.362660,-0.959649,1
3,NaN,NaN,0,0,0.514251,0,1,0,2,0,2,2,0,0,1,0,0,-0.746535,-0.195248,0
4,NaN,NaN,0,0,-1.236724,1,0,1,0,0,0,0,0,0,0,1,2,0.197365,-0.940457,1

In [ ]:
#Hello checking if github contributions working or nah